# Site settings
title: Ria Ivandic
email: ria.ivandic@kcl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD Candidate in the Department of Political Economy at King's College London.
  My research interest are political economy and applied econometrics.  
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://riai.github.io/riaivandic/" # the base hostname & protocol for your site
twitter_username: ecklekctic
github_username:  riai
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
